default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: ai_flash_dev

test:
  <<: *default
  database: ai_flash_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
